## PROG8245 Assignment 1: (Total Marks 100)
## Start on 16th of September- Due on 27th of September

- TODO: write your name and ID below
- Name: **Khushbu Nileshkumar Lad**
- ID: **9027375**
- Kindly note that this assignment is to be solved by yourself, without the use of AI and chatbots.
- If chatbot usage is detected, the penalty that is discussed in Week 1 slides will apply.
- Each code block will have a Todo comment which explains the functionality, expected input, and expected output of the function.
- There are 10 marks in this assignment for assuring that the code couldn't be broken (no errors can be thrown, please consider mathematical and logical errors)
- There are 10 marks in this assignment for commenting and code readability.


### Part 1: Python Basics

#### Question 1:

In [2]:

def total_price(price, tax):
    # 3 marks
    # TODO: write the functionality of the code where
    #  you are taking as an input a price of an item and the
    #  tax in decimal (13% tax will be given as 0.13),
    #  you should return the taxedPrice of that item
    #  which will be the total price after tax a customer must pay
    # (The price of the item plus the applicable taxes)

    # Taxes price = Price + ( tax percentage or price )
    # Here, Tax is passed as 0.xx so no need to device by 100 
    return float(price + tax*price)

print(f"Price : 100.00 \t\t\t Tax : 0.10 (10%)  \t\t Taxed Price : { total_price(100,0.10)}")
print(f"Price : 1270.00 \t\t Tax : 0.12 (12%)  \t\t taxed Price : { total_price(1270,0.12)}")
print(f"Price : 10786.00 \t\t Tax : 0.153 (15.3%)  \t\t taxed Price : { total_price(10786,0.153)}")
print(f"Price : 85.00 \t\t\t Tax : 0.6678 (66.78%)  \t taxed Price : { total_price(85,0.6678)}")



Price : 100.00 			 Tax : 0.10 (10%)  		 Taxed Price : 110.0
Price : 1270.00 		 Tax : 0.12 (12%)  		 taxed Price : 1422.4
Price : 10786.00 		 Tax : 0.153 (15.3%)  		 taxed Price : 12436.258
Price : 85.00 			 Tax : 0.6678 (66.78%)  	 taxed Price : 141.763


#### Question 2:

In [3]:
def divisible_by(x, y):
    # 3 marks
    # TODO: write a function that returns True if x is divisible by y,
    #  and returns False OTHERWISE (all other cases).
    try:
        # Check if value can be parsed in float 
        x = float(x)
        y = float(y)
        # Check if y is not 0 as divide by 0 = infinate throws exception
        if(y!=0):
            return True
        else:
            return False
    except ValueError:
        return False

print(f"x = 10 \t\t y = 10 \t division : {divisible_by(10,10)}")
print(f"x = 10 \t\t y = 0 \t\t division : {divisible_by(10,0)}")
print(f"x = 0 \t\t y = 10 \t division : {divisible_by(10,0)}")
print(f"x = 40 \t\t y = 32 \t division : {divisible_by(40,32)}")
print(f"x = 192 \t y = 4 \t\t division : {divisible_by(192,4)}")
print(f"x = abc \t y = a \t\t division : {divisible_by('abc','a')}")
print(f"x = 100 \t y = a \t\t division : {divisible_by(100,'a')}")

x = 10 		 y = 10 	 division : True
x = 10 		 y = 0 		 division : False
x = 0 		 y = 10 	 division : False
x = 40 		 y = 32 	 division : True
x = 192 	 y = 4 		 division : True
x = abc 	 y = a 		 division : False
x = 100 	 y = a 		 division : False


#### Question 3:

In [4]:
def basic_calculator(x, y, operator):
    # 5 marks
    # TODO: write the functionality of the code where you are
    #  coding a basic calculator that performs basic addition "+", subtraction "-",
    #  multiplication "*", division "/", modulus "%" and integer division "//"
    #  the function must apply the operator to x and y for example:
    #  basicCalculator(10, 15, "*") should apply 10*15 and save it to the result variable
    #  NOTE: YOU NEED TO HANDLE DIVISION ERRORS BY RETURNING A STRING WITH THE WORD "error"
    #  NOTE: YOU NEED TO HANDLE AN INVALID OPERATOR BY RETURNING A STRING HAVING THE WORD "invalid"

    print(f" x \t: {x} \r\n y \t: {y} \r\n op \t: {operator}")
    try:
        # Check if value can be parsed in float 
        x = float(x)
        y = float(y)
    except ValueError:
        return "x and y must be integer or decimal values"
    result = 0
    if operator == '+':
        result = x + y
    elif operator == '-':
        result = x - y
    elif operator == '*':
        result = x * y
    elif operator == '/':
        if(y==0):
            return "error : unable to divide by 0" 
        result = x / y
    else:
        return "Invalid Operator : Allowed operator are addition '+', subtraction '-', multiplication '*' and division '/'"

    return f"{x} {operator} {y} = {result}"


print(f"Output : {basic_calculator(10,15,'+')} \r\n")
print(f"Output : {basic_calculator(10,15,'-')} \r\n")
print(f"Output : {basic_calculator(10,15,'*')} \r\n")
print(f"Output : {basic_calculator(10,15,'/')} \r\n")
print(f"Output : {basic_calculator(10,0,'/')} \r\n")
print(f"Output : {basic_calculator('a',15,'+')} \r\n")
print(f"Output : {basic_calculator('a','a','+')} \r\n")

 x 	: 10 
 y 	: 15 
 op 	: +
Output : 10.0 + 15.0 = 25.0 

 x 	: 10 
 y 	: 15 
 op 	: -
Output : 10.0 - 15.0 = -5.0 

 x 	: 10 
 y 	: 15 
 op 	: *
Output : 10.0 * 15.0 = 150.0 

 x 	: 10 
 y 	: 15 
 op 	: /
Output : 10.0 / 15.0 = 0.6666666666666666 

 x 	: 10 
 y 	: 0 
 op 	: /
Output : error : unable to divide by 0 

 x 	: a 
 y 	: 15 
 op 	: +
Output : x and y must be integer or decimal values 

 x 	: a 
 y 	: a 
 op 	: +
Output : x and y must be integer or decimal values 



#### Question 4:

In [5]:
def sum_of_even(numbers_list):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a list of numbers
    # returning the sum of even numbers in the list
    # NOTE: YOU NEED TO HANDLE ERRORS OF GIVING LIST OF STRINGS OR/AND
    #  STRINGS WITH NUMBERS by returning "invalid"
    # sum_of_even([1,2,3,4,5,6]) = 12
    
    sum = 0
    for n in numbers_list:
        try:
            # Check if input is number
            n = float(n)
            # Check if number is even
            if(n%2 ==0):
                sum += float(n)
        except:
            # Print invalid input
            print(f"invalid input : {n}")
    
    # Print result
    print(f"Sum of valid even input numbers : {sum}")
    return 0

sum_of_even([1,2,3,4,5,6])
sum_of_even([1,'a',8,'ls',5,76])

Sum of valid even input numbers : 12.0
invalid input : a
invalid input : ls
Sum of valid even input numbers : 84.0


0

#### Question 5:

In [6]:
def reverse_string(input_string):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a string
    # returns the reverse of the string
    # reverse_string("hello") = "olleh"
    # NOTE: Numbers should be handled as strings ex: 123 returns "321"
    return str(input_string)[::-1]


print(reverse_string("hello"))
print(reverse_string("hello123"))
print(reverse_string(1234567890))


olleh
321olleh
0987654321


#### Question 6:

In [7]:
def diamond_string(length):
    # 5 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a POSITIVE ODD length
    # saves in a string the diamond as follows:
    # diamond_string(5)
    #   *
    #  ***
    # *****
    #  ***
    #   *
    # NOTE: The input must be positive odd, if not return empty string "" 
    print(f"Input length : {length}")
    
    if(type(length)!=int or length%2==0):
        return "Invalid input : Only odd numbers can function"
    
    diamond_str=""
    # Incremental loop for first 50% tringle  
    for n in range(1,length+1,2):
        row = ""
        # for loop logic for space 
        for l in range(length-(n+1),0,-2):
            row+=" "
        # for loop logic for * 
        for k in range(1,n+1):
            row+="*"
        diamond_str += row + "\r\n"
    
    # Decremental loop for reverse 50% tringle  
    for n in range(length-2,0,-2):
        row = ""
        # for loop logic for space 
        for l in range(length-(n+1),0,-2):
            row+=" "
        # for loop logic for *
        for k in range(1,n+1):
            row+="*"
        diamond_str += row + "\r\n"

    return diamond_str


print(diamond_string(5))
print(diamond_string(13))
print(diamond_string(6))
print(diamond_string("abc"))


Input length : 5
  *
 ***
*****
 ***
  *

Input length : 13
      *
     ***
    *****
   *******
  *********
 ***********
*************
 ***********
  *********
   *******
    *****
     ***
      *

Input length : 6
Invalid input : Only odd numbers can function
Input length : abc
Invalid input : Only odd numbers can function


#### Question 7:

In [8]:
def longest_consecutive_subarray(number_array):
    # 8 marks
    # TODO: write the functionality of the code where you are
    # taking as an input an array of REAL NUMBERS
    # return the length of the longest subarray that could be
    # built using the input
    # longest_consecutive_subarray([100, 4, 200, 1, 3, 2]) = 4
    # Function should return 4 which represents in this case
    # the longest_consecutive_subarray that could be built [1,2,3,4]
    # You can't use Built in Sorting!
    # Note: - If any error exists in the input, "error" should be returned
    #       - The difference between any 2 consecuetive numbers is 1.

    print(f"\r\nInput\t : {number_array}")
    # Numbers which are already checked
    ignore_list = []
    # count for each set if consicutive numbers
    searies_list = []
    # Consider minimum length of series is 1
    lcs = 1
    while(len(number_array)>0):
        # Find minimum 
        min_value = min(number_array)
        # Next consicutive number is found in original list so increment length of current series
        if(len(ignore_list)>0 and ignore_list[-1]+1 == min_value):
            lcs +=1
        else: # add length of last series in available lengths and reset length variable to 1 
            searies_list.append(lcs)
            lcs=1
        # Remove minimum value from original array and push it to another array to reduce itrations
        ignore_list.append(min_value)
        number_array.remove(min_value)
    # Print sorted data - for testing
    print(f"Sorted\t : {ignore_list}")
    return max(searies_list)

print(f"longest consecutive subarray : { longest_consecutive_subarray([100, 4, 200, 1, 3, 2])}")
print(f"longest consecutive subarray : { longest_consecutive_subarray([21,91, 71,92, 72,209, 22,208, 73, 23, 90,93,207,95,210,99,94,206])}")


Input	 : [100, 4, 200, 1, 3, 2]
Sorted	 : [1, 2, 3, 4, 100, 200]
longest consecutive subarray : 4

Input	 : [21, 91, 71, 92, 72, 209, 22, 208, 73, 23, 90, 93, 207, 95, 210, 99, 94, 206]
Sorted	 : [21, 22, 23, 71, 72, 73, 90, 91, 92, 93, 94, 95, 99, 206, 207, 208, 209, 210]
longest consecutive subarray : 6


#### Question 8 (Challenging):

In [9]:
def can_be_segmented(input_string, word_dict):
    # 15 marks
    # TODO: Write the functionality of the code where you
    # are given as an input a string and a word_dict
    # Your target is to return True, if input_string can be segmented
    # (broken-down) into a sequence of one or more dictionary words
    # otherwise return False
    # Sample Input: can_be_segmented("applepenapple", {'apple','pen'}) ==> True
    # Sample Input: can_be_segmented("catsandog", {'cats','dog','sand','and','cat'}) ==> False
    # Hint: You can start by checking which prefix exist in the dictionary, and call the same function recursively
    # on the remaining string.
    print(f"\r\nInput String \t\t: {input_string}")
    print(f"Word Disctionary \t: {word_dict}")

    for word in word_dict:
        if(input_string.find(word)>=0):
            input_string = input_string.replace(word,"")
        else:
            return False
    return True

print(f"Result \t\t\t : {can_be_segmented("applepenapple", {'apple','pen'})}")
print(f"Result \t\t\t : {can_be_segmented("catsandog", {'cats','dog','sand','and','cat'})}")


Input String 		: applepenapple
Word Disctionary 	: {'apple', 'pen'}
Result 			 : True

Input String 		: catsandog
Word Disctionary 	: {'sand', 'and', 'cat', 'dog', 'cats'}
Result 			 : False


### Part 2: Numpy Basics: 
- In this Part of the assignment, you are <b>ONLY ALLOWED</b> to use Numpy and its functions. 
- You are not expected to use Loops.

In [10]:
import numpy as np

#### Question 9:

In [11]:
def no_zeros(array_input):
    # 3 marks
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: np.array([1,2,3,4,5,6,0]) Sample Output: False
    ## Sample input: np.array([1,2,3,4,5,6]) Sample Output: True
    print(f"\r\nInput : {array_input}")
    return (0 in array_input)

print(f"Array has Zeroes : {no_zeros(np.array([1,2,3,4,5,6,0]))}")
print(f"Array has Zeroes : {no_zeros(np.array([1,2,3,4,5,6]))}")


Input : [1 2 3 4 5 6 0]
Array has Zeroes : True

Input : [1 2 3 4 5 6]
Array has Zeroes : False


#### Question 10:

In [12]:
def two_dimensions(n):
    # 7 marks
    ## TODO: This function should create a 2d Array of shape n*n for any positive number
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    print(f"\r\nArray : {n} x {n}")
    result = np.ones((n,n))
    result[1:-1, 1:-1] = 0
    return result

print(two_dimensions(2))
print(two_dimensions(3))
print(two_dimensions(6))
    


Array : 2 x 2
[[1. 1.]
 [1. 1.]]

Array : 3 x 3
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

Array : 6 x 6
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### Question 11:

In [28]:
def random_generation(n,min,max):
    # 5 marks
    # TODO: Write a function that takes as an input
    # Dimension of 2d Array n, min and max
    # Generate an n*n array with random numbers between
    # min and max inclusive
    # Such that no element is duplicated
    # return numpy array
    # Implement this function using ONLY numpy methods
    # Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]f
    print(f"\r\nn : { n } \t\t min : {min}\t\tmax : {max}")
    # create random unique numbers array
    unique_random_numbers = np.random.choice(range(min, max), size=(n*n), replace=False)
    # Split the array
    return np.array(np.hsplit(unique_random_numbers,n))

print(f"Random Array : {3} x {3} \r\n{random_generation(3,0,12)}")
print(f"Random Array : {5} x {5} \r\n{random_generation(5,10,122)}")


n : 3 		 min : 0		max : 12
Random Array : 3 x 3 
[[ 1  2  8]
 [10  5  7]
 [11  0  3]]

n : 5 		 min : 10		max : 122
Random Array : 5 x 5 
[[ 63  77  75  43  13]
 [ 36  19 119  99  18]
 [ 11  28  32  21  12]
 [ 91  79 116  57  22]
 [ 23  35 104  97  84]]


#### Question 12:

In [38]:
def matrix_border_sum(matrix):
    # 8 marks
    # TODO: Write a function that takes as an input a matrix
    # and return the sum of all elements in the borders
    # Implement this function using ONLY numpy methods
    # Sample Input: np.array([[1,2,3],
    #                         [4,5,6],
    #                         [7,8,9]])
    # Output: matrix_border_sum(matrix) =  1+2+3+4+6+7+8+9 = 40
    print(f"\r\n Input :\r\n{matrix}")
    return (np.sum(matrix[0]) + np.sum(matrix[-1]) + np.sum(matrix[1:-1,[0]]) + np.sum(matrix[1:-1,[-1]]))

print(f"Sum : {matrix_border_sum(np.array([[1,2,3],
                            [4,5,6],
                            [7,8,9]]))}")

print(f"Sum : {matrix_border_sum(np.array([[1,1,1,1],
                            [1,1,1,1],
                            [1,1,1,1],
                            [1,1,1,1]]))}")



 Input :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum : 40

 Input :
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Sum : 12


### Part 3: Pandas

In [15]:
import pandas as pd

#### Question 13 (12 marks): 
- Using RegularSeasonCompactResults.csv and Teams.csv apply the following functionalities

In [59]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter to show if there are any draw matches
# 2- Apply the filter to the dataframe
# 3- SHOW/PRINT the dataframe length or count (4 marks)
## TODO: Your code should be here

team_data = pd.read_csv('./Dataset/Teams.csv')
score_data = pd.read_csv('./Dataset/RegularSeasonCompactResults.csv')

draw_filter = score_data['Wscore'] == score_data['Lscore']
print(f"Draw matches count : {len(score_data[draw_filter])}")


Draw matches count : 0


In [63]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter showing the entries where the winningteamID= 1400- (last two digits of your id)
# 2- Create another filter for the season of 2013
# 3- Apply the filter to the dataframe
# 4- Show the resulted dataframe (4 marks)
# (Example: IF your id is 8000021, the winning team id = 1400-21= 1379)
# TODO: Your code should be here

winningTeam_filter = score_data['Wteam'] == (1400-75)
season_filter = score_data['Season'] == 2013
result = score_data[season_filter & winningTeam_filter]
print(result)


        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
123988    2013       5   1325      81   1339      52    H      0
124242    2013      11   1325      85   1423      47    H      0
124369    2013      13   1325      73   1459      50    H      0
124465    2013      15   1325      75   1214      67    H      0
124658    2013      19   1325      73   1350      48    H      0
124800    2013      23   1325      69   1382      64    H      0
125200    2013      33   1325      78   1324      61    H      0
125653    2013      47   1325      93   1271      57    H      0
126118    2013      61   1325      94   1267      57    H      0
126256    2013      65   1325      86   1138      68    H      0
126435    2013      68   1325      61   1444      59    A      0
126574    2013      72   1325      81   1296      63    H      0
126758    2013      75   1325      76   1405      67    H      0
126899    2013      79   1325      74   1275      62    A      0
127082    2013      82   

In [62]:
# Using RegularSeasonCompactResults.csv & Teams.csv
# 1- Load and merge both dataframes
# 2- Where the merge is on WinningTeamId (RegularSeasonCompactResults) and TeamId (Teams.csv)
# 3- Name the dataframe: DFCombined
# 4- Show the top 3 rows (4 marks)
# TODO: Your code should be here

joined_data = pd.merge(score_data,team_data,left_on="Wteam",right_on='Team_Id', how='inner')
joined_data.head(3)
# print(joined_data)

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Team_Id  \
0    1985      20   1228      81   1328      64    N      0     1228   
1    1985      25   1106      77   1354      70    H      0     1106   
2    1985      25   1112      63   1223      56    H      0     1112   

    Team_Name  
0    Illinois  
1  Alabama St  
2     Arizona

### References

Numpy.ones — NumPy v2.1 Manual. (n.d.). https://numpy.org/doc/stable/reference/generated/numpy.ones.html
